// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flashbots/amp-alerts-sink/publisher (interfaces: SlackApi)

// Package mock_publisher is a generated GoMock package.
package mock_publisher

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	slack "github.com/slack-go/slack"
)

// MockSlackApi is a mock of SlackApi interface.
type MockSlackApi struct {
	ctrl     *gomock.Controller
	recorder *MockSlackApiMockRecorder
}

// MockSlackApiMockRecorder is the mock recorder for MockSlackApi.
type MockSlackApiMockRecorder struct {
	mock *MockSlackApi
}

// NewMockSlackApi creates a new mock instance.
func NewMockSlackApi(ctrl *gomock.Controller) *MockSlackApi {
	mock := &MockSlackApi{ctrl: ctrl}
	mock.recorder = &MockSlackApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackApi) EXPECT() *MockSlackApiMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockSlackApi) AddReaction(arg0 string, arg1 slack.ItemRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockSlackApiMockRecorder) AddReaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockSlackApi)(nil).AddReaction), arg0, arg1)
}

// PostMessage mocks base method.
func (m *MockSlackApi) PostMessage(arg0 string, arg1 ...slack.MsgOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostMessage", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PostMessage indicates an expected call of PostMessage.
func (mr *MockSlackApiMockRecorder) PostMessage(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessage", reflect.TypeOf((*MockSlackApi)(nil).PostMessage), varargs...)
}

// RemoveReaction mocks base method.
func (m *MockSlackApi) RemoveReaction(arg0 string, arg1 slack.ItemRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockSlackApiMockRecorder) RemoveReaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockSlackApi)(nil).RemoveReaction), arg0, arg1)
}
