// Code generated by MockGen. DO NOT EDIT.
// Source: slack.go
//
// Generated by this command:
//
//	mockgen -package mock_publisher -destination ../mock/publisher/slack.go -source slack.go SlackApi
//

// Package mock_publisher is a generated GoMock package.
package mock_publisher

import (
	reflect "reflect"

	slack "github.com/slack-go/slack"
	gomock "go.uber.org/mock/gomock"
)

// MockSlackApi is a mock of SlackApi interface.
type MockSlackApi struct {
	ctrl     *gomock.Controller
	recorder *MockSlackApiMockRecorder
	isgomock struct{}
}

// MockSlackApiMockRecorder is the mock recorder for MockSlackApi.
type MockSlackApiMockRecorder struct {
	mock *MockSlackApi
}

// NewMockSlackApi creates a new mock instance.
func NewMockSlackApi(ctrl *gomock.Controller) *MockSlackApi {
	mock := &MockSlackApi{ctrl: ctrl}
	mock.recorder = &MockSlackApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackApi) EXPECT() *MockSlackApiMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockSlackApi) AddReaction(name string, item slack.ItemRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", name, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockSlackApiMockRecorder) AddReaction(name, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockSlackApi)(nil).AddReaction), name, item)
}

// PostMessage mocks base method.
func (m *MockSlackApi) PostMessage(channelID string, options ...slack.MsgOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{channelID}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostMessage", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PostMessage indicates an expected call of PostMessage.
func (mr *MockSlackApiMockRecorder) PostMessage(channelID any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{channelID}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessage", reflect.TypeOf((*MockSlackApi)(nil).PostMessage), varargs...)
}

// RemoveReaction mocks base method.
func (m *MockSlackApi) RemoveReaction(name string, item slack.ItemRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", name, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockSlackApiMockRecorder) RemoveReaction(name, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockSlackApi)(nil).RemoveReaction), name, item)
}
