// Code generated by MockGen. DO NOT EDIT.
// Source: webhook.go
//
// Generated by this command:
//
//	mockgen -package mock_publisher -destination ../mock/publisher/webhook.go -source webhook.go -mock_names httpClient=Mock_httpClient httpClient
//

// Package mock_publisher is a generated GoMock package.
package mock_publisher

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mock_httpClient is a mock of httpClient interface.
type Mock_httpClient struct {
	ctrl     *gomock.Controller
	recorder *Mock_httpClientMockRecorder
	isgomock struct{}
}

// Mock_httpClientMockRecorder is the mock recorder for Mock_httpClient.
type Mock_httpClientMockRecorder struct {
	mock *Mock_httpClient
}

// NewMock_httpClient creates a new mock instance.
func NewMock_httpClient(ctrl *gomock.Controller) *Mock_httpClient {
	mock := &Mock_httpClient{ctrl: ctrl}
	mock.recorder = &Mock_httpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_httpClient) EXPECT() *Mock_httpClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *Mock_httpClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *Mock_httpClientMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*Mock_httpClient)(nil).Do), req)
}
